<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GeoLgaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run(): void
    {
        //geo_lgas seeder
        DB::table('geo_lgas')->insert([
            ["name" => "Aba North", "geo_state_id" => 2],
            ["name" => "Aba South", "geo_state_id" => 2],
            ["name" => "Arochukwu", "geo_state_id" => 2],
            ["name" => "Bende", "geo_state_id" => 2],
            ["name" => "Ikwuano", "geo_state_id" => 2],
            ["name" => "Isiala Ngwa North", "geo_state_id" => 2],
            ["name" => "Isiala Ngwa South", "geo_state_id" => 2],
            ["name" => "Isuikwuato", "geo_state_id" => 2],
            ["name" => "Obi Ngwa", "geo_state_id" => 2],
            ["name" => "Ohafia", "geo_state_id" => 2],
            ["name" => "Osisioma", "geo_state_id" => 2],
            ["name" => "Ugwunagbo", "geo_state_id" => 2],
            ["name" => "Ukwa East", "geo_state_id" => 2],
            ["name" => "Ukwa West", "geo_state_id" => 2],
            ["name" => "Umuahia North", "geo_state_id" => 2],
            ["name" => "Umuahia South", "geo_state_id" => 2],
            ["name" => "Umu Nneochi", "geo_state_id" => 2],
            ["name" => "Demsa", "geo_state_id" => 3],
            ["name" => "Fufure", "geo_state_id" => 3],
            ["name" => "Ganye", "geo_state_id" => 3],
            ["name" => "Gayuk", "geo_state_id" => 3],
            ["name" => "Gombi", "geo_state_id" => 3],
            ["name" => "Grie", "geo_state_id" => 3],
            ["name" => "Hong", "geo_state_id" => 3],
            ["name" => "Jada", "geo_state_id" => 3],
            ["name" => "Larmurde", "geo_state_id" => 3],
            ["name" => "Madagali", "geo_state_id" => 3],
            ["name" => "Maiha", "geo_state_id" => 3],
            ["name" => "Mayo Belwa", "geo_state_id" => 3],
            ["name" => "Michika", "geo_state_id" => 3],
            ["name" => "Mubi North", "geo_state_id" => 3],
            ["name" => "Mubi South", "geo_state_id" => 3],
            ["name" => "Numan", "geo_state_id" => 3],
            ["name" => "Shelleng", "geo_state_id" => 3],
            ["name" => "Song", "geo_state_id" => 3],
            ["name" => "Toungo", "geo_state_id" => 3],
            ["name" => "Yola North", "geo_state_id" => 3],
            ["name" => "Yola South", "geo_state_id" => 3],
            ["name" => "Abak", "geo_state_id" => 4],
            ["name" => "Eastern Obolo", "geo_state_id" => 4],
            ["name" => "Eket", "geo_state_id" => 4],
            ["name" => "Esit Eket", "geo_state_id" => 4],
            ["name" => "Essien Udim", "geo_state_id" => 4],
            ["name" => "Etim Ekpo", "geo_state_id" => 4],
            ["name" => "Etinan", "geo_state_id" => 4],
            ["name" => "Ibeno", "geo_state_id" => 4],
            ["name" => "Ibesikpo Asutan", "geo_state_id" => 4],
            ["name" => "Ibiono-Ibom", "geo_state_id" => 4],
            ["name" => "Ika", "geo_state_id" => 4],
            ["name" => "Ikono", "geo_state_id" => 4],
            ["name" => "Ikot Abasi", "geo_state_id" => 4],
            ["name" => "Ikot Ekpene", "geo_state_id" => 4],
            ["name" => "Ini", "geo_state_id" => 4],
            ["name" => "Itu", "geo_state_id" => 4],
            ["name" => "Mbo", "geo_state_id" => 4],
            ["name" => "Mkpat-Enin", "geo_state_id" => 4],
            ["name" => "Nsit-Atai", "geo_state_id" => 4],
            ["name" => "Nsit-Ibom", "geo_state_id" => 4],
            ["name" => "Nsit-Ubium", "geo_state_id" => 4],
            ["name" => "Obot Akara", "geo_state_id" => 4],
            ["name" => "Okobo", "geo_state_id" => 4],
            ["name" => "Onna", "geo_state_id" => 4],
            ["name" => "Oron", "geo_state_id" => 4],
            ["name" => "Oruk Anam", "geo_state_id" => 4],
            ["name" => "Udung-Uko", "geo_state_id" => 4],
            ["name" => "Ukanafun", "geo_state_id" => 4],
            ["name" => "Uruan", "geo_state_id" => 4],
            ["name" => "Urue-Offong/Oruko", "geo_state_id" => 4],
            ["name" => "Uyo", "geo_state_id" => 4],
            ["name" => "Aguata", "geo_state_id" => 5],
            ["name" => "Anambra East", "geo_state_id" => 5],
            ["name" => "Anambra West", "geo_state_id" => 5],
            ["name" => "Anaocha", "geo_state_id" => 5],
            ["name" => "Awka North", "geo_state_id" => 5],
            ["name" => "Awka South", "geo_state_id" => 5],
            ["name" => "Ayamelum", "geo_state_id" => 5],
            ["name" => "Dunukofia", "geo_state_id" => 5],
            ["name" => "Ekwusigo", "geo_state_id" => 5],
            ["name" => "Idemili North", "geo_state_id" => 5],
            ["name" => "Idemili South", "geo_state_id" => 5],
            ["name" => "Ihiala", "geo_state_id" => 5],
            ["name" => "Njikoka", "geo_state_id" => 5],
            ["name" => "Nnewi North", "geo_state_id" => 5],
            ["name" => "Nnewi South", "geo_state_id" => 5],
            ["name" => "Ogbaru", "geo_state_id" => 5],
            ["name" => "Onitsha North", "geo_state_id" => 5],
            ["name" => "Onitsha South", "geo_state_id" => 5],
            ["name" => "Orumba North", "geo_state_id" => 5],
            ["name" => "Orumba South", "geo_state_id" => 5],
            ["name" => "Oyi", "geo_state_id" => 5],
            ["name" => "Alkaleri", "geo_state_id" => 6],
            ["name" => "Bauchi", "geo_state_id" => 6],
            ["name" => "Bogoro", "geo_state_id" => 6],
            ["name" => "Damban", "geo_state_id" => 6],
            ["name" => "Darazo", "geo_state_id" => 6],
            ["name" => "Dass", "geo_state_id" => 6],
            ["name" => "Gamawa", "geo_state_id" => 6],
            ["name" => "Ganjuwa", "geo_state_id" => 6],
            ["name" => "Giade", "geo_state_id" => 6],
            ["name" => "Itas/Gadau", "geo_state_id" => 6],
            ["name" => "Jama'are", "geo_state_id" => 6],
            ["name" => "Katagum", "geo_state_id" => 6],
            ["name" => "Kirfi", "geo_state_id" => 6],
            ["name" => "Misau", "geo_state_id" => 6],
            ["name" => "Ningi", "geo_state_id" => 6],
            ["name" => "Shira", "geo_state_id" => 6],
            ["name" => "Tafawa Balewa", "geo_state_id" => 6],
            ["name" => "Toro", "geo_state_id" => 6],
            ["name" => "Warji", "geo_state_id" => 6],
            ["name" => "Zaki", "geo_state_id" => 6],
            ["name" => "Brass", "geo_state_id" => 7],
            ["name" => "Ekeremor", "geo_state_id" => 7],
            ["name" => "Kolokuma/Opokuma", "geo_state_id" => 7],
            ["name" => "Nembe", "geo_state_id" => 7],
            ["name" => "Ogbia", "geo_state_id" => 7],
            ["name" => "Sagbama", "geo_state_id" => 7],
            ["name" => "Southern Ijaw", "geo_state_id" => 7],
            ["name" => "Yenagoa", "geo_state_id" => 7],
            ["name" => "Agatu", "geo_state_id" => 8],
            ["name" => "Apa", "geo_state_id" => 8],
            ["name" => "Ado", "geo_state_id" => 8],
            ["name" => "Buruku", "geo_state_id" => 8],
            ["name" => "Gboko", "geo_state_id" => 8],
            ["name" => "Guma", "geo_state_id" => 8],
            ["name" => "Gwer East", "geo_state_id" => 8],
            ["name" => "Gwer West", "geo_state_id" => 8],
            ["name" => "Katsina-Ala", "geo_state_id" => 8],
            ["name" => "Konshisha", "geo_state_id" => 8],
            ["name" => "Kwande", "geo_state_id" => 8],
            ["name" => "Logo", "geo_state_id" => 8],
            ["name" => "Makurdi", "geo_state_id" => 8],
            ["name" => "Obi", "geo_state_id" => 8],
            ["name" => "Ogbadibo", "geo_state_id" => 8],
            ["name" => "Ohimini", "geo_state_id" => 8],
            ["name" => "Oju", "geo_state_id" => 8],
            ["name" => "Okpokwu", "geo_state_id" => 8],
            ["name" => "Oturkpo", "geo_state_id" => 8],
            ["name" => "Tarka", "geo_state_id" => 8],
            ["name" => "Ukum", "geo_state_id" => 8],
            ["name" => "Ushongo", "geo_state_id" => 8],
            ["name" => "Vandeikya", "geo_state_id" => 8],
            ["name" => "Abadam", "geo_state_id" => 9],
            ["name" => "Askira/Uba", "geo_state_id" => 9],
            ["name" => "Bama", "geo_state_id" => 9],
            ["name" => "Bayo", "geo_state_id" => 9],
            ["name" => "Biu", "geo_state_id" => 9],
            ["name" => "Chibok", "geo_state_id" => 9],
            ["name" => "Damboa", "geo_state_id" => 9],
            ["name" => "Dikwa", "geo_state_id" => 9],
            ["name" => "Gubio", "geo_state_id" => 9],
            ["name" => "Guzamala", "geo_state_id" => 9],
            ["name" => "Gwoza", "geo_state_id" => 9],
            ["name" => "Hawul", "geo_state_id" => 9],
            ["name" => "Jere", "geo_state_id" => 9],
            ["name" => "Kaga", "geo_state_id" => 9],
            ["name" => "Kala/Balge", "geo_state_id" => 9],
            ["name" => "Konduga", "geo_state_id" => 9],
            ["name" => "Kukawa", "geo_state_id" => 9],
            ["name" => "Kwaya Kusar", "geo_state_id" => 9],
            ["name" => "Mafa", "geo_state_id" => 9],
            ["name" => "Magumeri", "geo_state_id" => 9],
            ["name" => "Maiduguri", "geo_state_id" => 9],
            ["name" => "Marte", "geo_state_id" => 9],
            ["name" => "Mobbar", "geo_state_id" => 9],
            ["name" => "Monguno", "geo_state_id" => 9],
            ["name" => "Ngala", "geo_state_id" => 9],
            ["name" => "Nganzai", "geo_state_id" => 9],
            ["name" => "Shani", "geo_state_id" => 9],
            ["name" => "Abi", "geo_state_id" => 10],
            ["name" => "Akamkpa", "geo_state_id" => 10],
            ["name" => "Akpabuyo", "geo_state_id" => 10],
            ["name" => "Bakassi", "geo_state_id" => 10],
            ["name" => "Bekwarra", "geo_state_id" => 10],
            ["name" => "Biase", "geo_state_id" => 10],
            ["name" => "Boki", "geo_state_id" => 10],
            ["name" => "Calabar Municipal", "geo_state_id" => 10],
            ["name" => "Calabar South", "geo_state_id" => 10],
            ["name" => "Etung", "geo_state_id" => 10],
            ["name" => "Ikom", "geo_state_id" => 10],
            ["name" => "Obanliku", "geo_state_id" => 10],
            ["name" => "Obubra", "geo_state_id" => 10],
            ["name" => "Obudu", "geo_state_id" => 10],
            ["name" => "Odukpani", "geo_state_id" => 10],
            ["name" => "Ogoja", "geo_state_id" => 10],
            ["name" => "Yakuur", "geo_state_id" => 10],
            ["name" => "Yala", "geo_state_id" => 10],
            ["name" => "Aniocha North", "geo_state_id" => 11],
            ["name" => "Aniocha South", "geo_state_id" => 11],
            ["name" => "Bomadi", "geo_state_id" => 11],
            ["name" => "Burutu", "geo_state_id" => 11],
            ["name" => "Ethiope East", "geo_state_id" => 11],
            ["name" => "Ethiope West", "geo_state_id" => 11],
            ["name" => "Ika North East", "geo_state_id" => 11],
            ["name" => "Ika South", "geo_state_id" => 11],
            ["name" => "Isoko North", "geo_state_id" => 11],
            ["name" => "Isoko South", "geo_state_id" => 11],
            ["name" => "Ndokwa East", "geo_state_id" => 11],
            ["name" => "Ndokwa West", "geo_state_id" => 11],
            ["name" => "Okpe", "geo_state_id" => 11],
            ["name" => "Oshimili North", "geo_state_id" => 11],
            ["name" => "Oshimili South", "geo_state_id" => 11],
            ["name" => "Patani", "geo_state_id" => 11],
            ["name" => "Sapele", "geo_state_id" => 11],
            ["name" => "Udu", "geo_state_id" => 11],
            ["name" => "Ughelli North", "geo_state_id" => 11],
            ["name" => "Ughelli South", "geo_state_id" => 11],
            ["name" => "Ukwuani", "geo_state_id" => 11],
            ["name" => "Uvwie", "geo_state_id" => 11],
            ["name" => "Warri North", "geo_state_id" => 11],
            ["name" => "Warri South", "geo_state_id" => 11],
            ["name" => "Warri South West", "geo_state_id" => 11],
            ["name" => "Abakaliki", "geo_state_id" => 12],
            ["name" => "Afikpo North", "geo_state_id" => 12],
            ["name" => "Afikpo South", "geo_state_id" => 12],
            ["name" => "Ebonyi", "geo_state_id" => 12],
            ["name" => "Ezza North", "geo_state_id" => 12],
            ["name" => "Ezza South", "geo_state_id" => 12],
            ["name" => "Ikwo", "geo_state_id" => 12],
            ["name" => "Ishielu", "geo_state_id" => 12],
            ["name" => "Ivo", "geo_state_id" => 12],
            ["name" => "Izzi", "geo_state_id" => 12],
            ["name" => "Ohaozara", "geo_state_id" => 12],
            ["name" => "Ohaukwu", "geo_state_id" => 12],
            ["name" => "Onicha", "geo_state_id" => 12],
            ["name" => "Akoko-Edo", "geo_state_id" => 13],
            ["name" => "Egor", "geo_state_id" => 13],
            ["name" => "Esan Central", "geo_state_id" => 13],
            ["name" => "Esan North-East", "geo_state_id" => 13],
            ["name" => "Esan South-East", "geo_state_id" => 13],
            ["name" => "Esan West", "geo_state_id" => 13],
            ["name" => "Etsako Central", "geo_state_id" => 13],
            ["name" => "Etsako East", "geo_state_id" => 13],
            ["name" => "Etsako West", "geo_state_id" => 13],
            ["name" => "Igueben", "geo_state_id" => 13],
            ["name" => "Ikpoba Okha", "geo_state_id" => 13],
            ["name" => "Orhionmwon", "geo_state_id" => 13],
            ["name" => "Oredo", "geo_state_id" => 13],
            ["name" => "Ovia North-East", "geo_state_id" => 13],
            ["name" => "Ovia South-West", "geo_state_id" => 13],
            ["name" => "Owan East", "geo_state_id" => 13],
            ["name" => "Owan West", "geo_state_id" => 13],
            ["name" => "Uhunmwonde", "geo_state_id" => 13],
            ["name" => "Ado Ekiti", "geo_state_id" => 14],
            ["name" => "Efon", "geo_state_id" => 14],
            ["name" => "Ekiti East", "geo_state_id" => 14],
            ["name" => "Ekiti South-West", "geo_state_id" => 14],
            ["name" => "Ekiti West", "geo_state_id" => 14],
            ["name" => "Emure", "geo_state_id" => 14],
            ["name" => "Gbonyin", "geo_state_id" => 14],
            ["name" => "Ido Osi", "geo_state_id" => 14],
            ["name" => "Ijero", "geo_state_id" => 14],
            ["name" => "Ikere", "geo_state_id" => 14],
            ["name" => "Ikole", "geo_state_id" => 14],
            ["name" => "Ilejemeje", "geo_state_id" => 14],
            ["name" => "Irepodun/Ifelodun", "geo_state_id" => 14],
            ["name" => "Ise/Orun", "geo_state_id" => 14],
            ["name" => "Moba", "geo_state_id" => 14],
            ["name" => "Oye", "geo_state_id" => 14],
            ["name" => "Aninri", "geo_state_id" => 15],
            ["name" => "Awgu", "geo_state_id" => 15],
            ["name" => "Enugu East", "geo_state_id" => 15],
            ["name" => "Enugu North", "geo_state_id" => 15],
            ["name" => "Enugu South", "geo_state_id" => 15],
            ["name" => "Ezeagu", "geo_state_id" => 15],
            ["name" => "Igbo Etiti", "geo_state_id" => 15],
            ["name" => "Igbo Eze North", "geo_state_id" => 15],
            ["name" => "Igbo Eze South", "geo_state_id" => 15],
            ["name" => "Isi Uzo", "geo_state_id" => 15],
            ["name" => "Nkanu East", "geo_state_id" => 15],
            ["name" => "Nkanu West", "geo_state_id" => 15],
            ["name" => "Nsukka", "geo_state_id" => 15],
            ["name" => "Oji River", "geo_state_id" => 15],
            ["name" => "Udenu", "geo_state_id" => 15],
            ["name" => "Udi", "geo_state_id" => 15],
            ["name" => "Uzo Uwani", "geo_state_id" => 15],
            ["name" => "Akko", "geo_state_id" => 16],
            ["name" => "Balanga", "geo_state_id" => 16],
            ["name" => "Billiri", "geo_state_id" => 16],
            ["name" => "Dukku", "geo_state_id" => 16],
            ["name" => "Funakaye", "geo_state_id" => 16],
            ["name" => "Gombe", "geo_state_id" => 16],
            ["name" => "Kaltungo", "geo_state_id" => 16],
            ["name" => "Kwami", "geo_state_id" => 16],
            ["name" => "Nafada", "geo_state_id" => 16],
            ["name" => "Shongom", "geo_state_id" => 16],
            ["name" => "Yamaltu/Deba", "geo_state_id" => 16],
            ["name" => "Aboh Mbaise", "geo_state_id" => 17],
            ["name" => "Ahiazu Mbaise", "geo_state_id" => 17],
            ["name" => "Ehime Mbano", "geo_state_id" => 17],
            ["name" => "Ezinihitte", "geo_state_id" => 17],
            ["name" => "Ideato North", "geo_state_id" => 17],
            ["name" => "Ideato South", "geo_state_id" => 17],
            ["name" => "Ihitte/Uboma", "geo_state_id" => 17],
            ["name" => "Ikeduru", "geo_state_id" => 17],
            ["name" => "Isiala Mbano", "geo_state_id" => 17],
            ["name" => "Isu", "geo_state_id" => 17],
            ["name" => "Mbaitoli", "geo_state_id" => 17],
            ["name" => "Ngor Okpala", "geo_state_id" => 17],
            ["name" => "Njaba", "geo_state_id" => 17],
            ["name" => "Nkwerre", "geo_state_id" => 17],
            ["name" => "Nwangele", "geo_state_id" => 17],
            ["name" => "Obowo", "geo_state_id" => 17],
            ["name" => "Oguta", "geo_state_id" => 17],
            ["name" => "Ohaji/Egbema", "geo_state_id" => 17],
            ["name" => "Okigwe", "geo_state_id" => 17],
            ["name" => "Orlu", "geo_state_id" => 17],
            ["name" => "Orsu", "geo_state_id" => 17],
            ["name" => "Oru East", "geo_state_id" => 17],
            ["name" => "Oru West", "geo_state_id" => 17],
            ["name" => "Owerri Municipal", "geo_state_id" => 17],
            ["name" => "Owerri North", "geo_state_id" => 17],
            ["name" => "Owerri West", "geo_state_id" => 17],
            ["name" => "Unuimo", "geo_state_id" => 17],
            ["name" => "Auyo", "geo_state_id" => 18],
            ["name" => "Babura", "geo_state_id" => 18],
            ["name" => "Biriniwa", "geo_state_id" => 18],
            ["name" => "Birnin Kudu", "geo_state_id" => 18],
            ["name" => "Buji", "geo_state_id" => 18],
            ["name" => "Dutse", "geo_state_id" => 18],
            ["name" => "Gagarawa", "geo_state_id" => 18],
            ["name" => "Garki", "geo_state_id" => 18],
            ["name" => "Gumel", "geo_state_id" => 18],
            ["name" => "Guri", "geo_state_id" => 18],
            ["name" => "Gwaram", "geo_state_id" => 18],
            ["name" => "Gwiwa", "geo_state_id" => 18],
            ["name" => "Hadejia", "geo_state_id" => 18],
            ["name" => "Jahun", "geo_state_id" => 18],
            ["name" => "Kafin Hausa", "geo_state_id" => 18],
            ["name" => "Kazaure", "geo_state_id" => 18],
            ["name" => "Kiri Kasama", "geo_state_id" => 18],
            ["name" => "Kiyawa", "geo_state_id" => 18],
            ["name" => "Kaugama", "geo_state_id" => 18],
            ["name" => "Maigatari", "geo_state_id" => 18],
            ["name" => "Malam Madori", "geo_state_id" => 18],
            ["name" => "Miga", "geo_state_id" => 18],
            ["name" => "Ringim", "geo_state_id" => 18],
            ["name" => "Roni", "geo_state_id" => 18],
            ["name" => "Sule Tankarkar", "geo_state_id" => 18],
            ["name" => "Taura", "geo_state_id" => 18],
            ["name" => "Yankwashi", "geo_state_id" => 18],
            ["name" => "Birnin Gwari", "geo_state_id" => 19],
            ["name" => "Chikun", "geo_state_id" => 19],
            ["name" => "Giwa", "geo_state_id" => 19],
            ["name" => "Igabi", "geo_state_id" => 19],
            ["name" => "Ikara", "geo_state_id" => 19],
            ["name" => "Jaba", "geo_state_id" => 19],
            ["name" => "Jema'a", "geo_state_id" => 19],
            ["name" => "Kachia", "geo_state_id" => 19],
            ["name" => "Kaduna North", "geo_state_id" => 19],
            ["name" => "Kaduna South", "geo_state_id" => 19],
            ["name" => "Kagarko", "geo_state_id" => 19],
            ["name" => "Kajuru", "geo_state_id" => 19],
            ["name" => "Kaura", "geo_state_id" => 19],
            ["name" => "Kauru", "geo_state_id" => 19],
            ["name" => "Kubau", "geo_state_id" => 19],
            ["name" => "Kudan", "geo_state_id" => 19],
            ["name" => "Lere", "geo_state_id" => 19],
            ["name" => "Makarfi", "geo_state_id" => 19],
            ["name" => "Sabon Gari", "geo_state_id" => 19],
            ["name" => "Sanga", "geo_state_id" => 19],
            ["name" => "Soba", "geo_state_id" => 19],
            ["name" => "Zangon Kataf", "geo_state_id" => 19],
            ["name" => "Zaria", "geo_state_id" => 19],
            ["name" => "Ajingi", "geo_state_id" => 20],
            ["name" => "Albasu", "geo_state_id" => 20],
            ["name" => "Bagwai", "geo_state_id" => 20],
            ["name" => "Bebeji", "geo_state_id" => 20],
            ["name" => "Bichi", "geo_state_id" => 20],
            ["name" => "Bunkure", "geo_state_id" => 20],
            ["name" => "Dala", "geo_state_id" => 20],
            ["name" => "Dambatta", "geo_state_id" => 20],
            ["name" => "Dawakin Kudu", "geo_state_id" => 20],
            ["name" => "Dawakin Tofa", "geo_state_id" => 20],
            ["name" => "Doguwa", "geo_state_id" => 20],
            ["name" => "Fagge", "geo_state_id" => 20],
            ["name" => "Gabasawa", "geo_state_id" => 20],
            ["name" => "Garko", "geo_state_id" => 20],
            ["name" => "Garun Mallam", "geo_state_id" => 20],
            ["name" => "Gaya", "geo_state_id" => 20],
            ["name" => "Gezawa", "geo_state_id" => 20],
            ["name" => "Gwale", "geo_state_id" => 20],
            ["name" => "Gwarzo", "geo_state_id" => 20],
            ["name" => "Kabo", "geo_state_id" => 20],
            ["name" => "Kano Municipal", "geo_state_id" => 20],
            ["name" => "Karaye", "geo_state_id" => 20],
            ["name" => "Kibiya", "geo_state_id" => 20],
            ["name" => "Kiru", "geo_state_id" => 20],
            ["name" => "Kumbotso", "geo_state_id" => 20],
            ["name" => "Kunchi", "geo_state_id" => 20],
            ["name" => "Kura", "geo_state_id" => 20],
            ["name" => "Madobi", "geo_state_id" => 20],
            ["name" => "Makoda", "geo_state_id" => 20],
            ["name" => "Minjibir", "geo_state_id" => 20],
            ["name" => "Nasarawa", "geo_state_id" => 20],
            ["name" => "Rano", "geo_state_id" => 20],
            ["name" => "Rimin Gado", "geo_state_id" => 20],
            ["name" => "Rogo", "geo_state_id" => 20],
            ["name" => "Shanono", "geo_state_id" => 20],
            ["name" => "Sumaila", "geo_state_id" => 20],
            ["name" => "Takai", "geo_state_id" => 20],
            ["name" => "Tarauni", "geo_state_id" => 20],
            ["name" => "Tofa", "geo_state_id" => 20],
            ["name" => "Tsanyawa", "geo_state_id" => 20],
            ["name" => "Tudun Wada", "geo_state_id" => 20],
            ["name" => "Ungogo", "geo_state_id" => 20],
            ["name" => "Warawa", "geo_state_id" => 20],
            ["name" => "Wudil", "geo_state_id" => 20],
            ["name" => "Bakori", "geo_state_id" => 21],
            ["name" => "Batagarawa", "geo_state_id" => 21],
            ["name" => "Batsari", "geo_state_id" => 21],
            ["name" => "Baure", "geo_state_id" => 21],
            ["name" => "Bindawa", "geo_state_id" => 21],
            ["name" => "Charanchi", "geo_state_id" => 21],
            ["name" => "Dandume", "geo_state_id" => 21],
            ["name" => "Danja", "geo_state_id" => 21],
            ["name" => "Dan Musa", "geo_state_id" => 21],
            ["name" => "Daura", "geo_state_id" => 21],
            ["name" => "Dutsi", "geo_state_id" => 21],
            ["name" => "Dutsin Ma", "geo_state_id" => 21],
            ["name" => "Faskari", "geo_state_id" => 21],
            ["name" => "Funtua", "geo_state_id" => 21],
            ["name" => "Ingawa", "geo_state_id" => 21],
            ["name" => "Jibia", "geo_state_id" => 21],
            ["name" => "Kafur", "geo_state_id" => 21],
            ["name" => "Kaita", "geo_state_id" => 21],
            ["name" => "Kankara", "geo_state_id" => 21],
            ["name" => "Kankia", "geo_state_id" => 21],
            ["name" => "Katsina", "geo_state_id" => 21],
            ["name" => "Kurfi", "geo_state_id" => 21],
            ["name" => "Kusada", "geo_state_id" => 21],
            ["name" => "Mai'Adua", "geo_state_id" => 21],
            ["name" => "Malumfashi", "geo_state_id" => 21],
            ["name" => "Mani", "geo_state_id" => 21],
            ["name" => "Mashi", "geo_state_id" => 21],
            ["name" => "Matazu", "geo_state_id" => 21],
            ["name" => "Musawa", "geo_state_id" => 21],
            ["name" => "Rimi", "geo_state_id" => 21],
            ["name" => "Sabuwa", "geo_state_id" => 21],
            ["name" => "Safana", "geo_state_id" => 21],
            ["name" => "Sandamu", "geo_state_id" => 21],
            ["name" => "Zango", "geo_state_id" => 21],
            ["name" => "Aleiro", "geo_state_id" => 22],
            ["name" => "Arewa Dandi", "geo_state_id" => 22],
            ["name" => "Argungu", "geo_state_id" => 22],
            ["name" => "Augie", "geo_state_id" => 22],
            ["name" => "Bagudo", "geo_state_id" => 22],
            ["name" => "Birnin Kebbi", "geo_state_id" => 22],
            ["name" => "Bunza", "geo_state_id" => 22],
            ["name" => "Dandi", "geo_state_id" => 22],
            ["name" => "Fakai", "geo_state_id" => 22],
            ["name" => "Gwandu", "geo_state_id" => 22],
            ["name" => "Jega", "geo_state_id" => 22],
            ["name" => "Kalgo", "geo_state_id" => 22],
            ["name" => "Koko/Besse", "geo_state_id" => 22],
            ["name" => "Maiyama", "geo_state_id" => 22],
            ["name" => "Ngaski", "geo_state_id" => 22],
            ["name" => "Sakaba", "geo_state_id" => 22],
            ["name" => "Shanga", "geo_state_id" => 22],
            ["name" => "Suru", "geo_state_id" => 22],
            ["name" => "Wasagu/Danko", "geo_state_id" => 22],
            ["name" => "Yauri", "geo_state_id" => 22],
            ["name" => "Zuru", "geo_state_id" => 22],
            ["name" => "Adavi", "geo_state_id" => 23],
            ["name" => "Ajaokuta", "geo_state_id" => 23],
            ["name" => "Ankpa", "geo_state_id" => 23],
            ["name" => "Bassa", "geo_state_id" => 23],
            ["name" => "Dekina", "geo_state_id" => 23],
            ["name" => "Ibaji", "geo_state_id" => 23],
            ["name" => "Idah", "geo_state_id" => 23],
            ["name" => "Igalamela Odolu", "geo_state_id" => 23],
            ["name" => "Ijumu", "geo_state_id" => 23],
            ["name" => "Kabba/Bunu", "geo_state_id" => 23],
            ["name" => "Kogi", "geo_state_id" => 23],
            ["name" => "Lokoja", "geo_state_id" => 23],
            ["name" => "Mopa Muro", "geo_state_id" => 23],
            ["name" => "Ofu", "geo_state_id" => 23],
            ["name" => "Ogori/Magongo", "geo_state_id" => 23],
            ["name" => "Okehi", "geo_state_id" => 23],
            ["name" => "Okene", "geo_state_id" => 23],
            ["name" => "Olamaboro", "geo_state_id" => 23],
            ["name" => "Omala", "geo_state_id" => 23],
            ["name" => "Yagba East", "geo_state_id" => 23],
            ["name" => "Yagba West", "geo_state_id" => 23],
            ["name" => "Asa", "geo_state_id" => 23],
            ["name" => "Baruten", "geo_state_id" => 23],
            ["name" => "Edu", "geo_state_id" => 24],
            ["name" => "Ekiti", "geo_state_id" => 24],
            ["name" => "Ifelodun", "geo_state_id" => 24],
            ["name" => "Ilorin East", "geo_state_id" => 24],
            ["name" => "Ilorin South", "geo_state_id" => 24],
            ["name" => "Ilorin West", "geo_state_id" => 24],
            ["name" => "Irepodun", "geo_state_id" => 24],
            ["name" => "Isin", "geo_state_id" => 24],
            ["name" => "Kaiama", "geo_state_id" => 24],
            ["name" => "Moro", "geo_state_id" => 24],
            ["name" => "Offa", "geo_state_id" => 24],
            ["name" => "Oke Ero", "geo_state_id" => 24],
            ["name" => "Oyun", "geo_state_id" => 24],
            ["name" => "Pategi", "geo_state_id" => 24],
            ["name" => "Agege", "geo_state_id" => 25],
            ["name" => "Ajeromi-Ifelodun", "geo_state_id" => 25],
            ["name" => "Alimosho", "geo_state_id" => 25],
            ["name" => "Amuwo-Odofin", "geo_state_id" => 25],
            ["name" => "Apapa", "geo_state_id" => 25],
            ["name" => "Badagry", "geo_state_id" => 25],
            ["name" => "Epe", "geo_state_id" => 25],
            ["name" => "Eti Osa", "geo_state_id" => 25],
            ["name" => "Ibeju-Lekki", "geo_state_id" => 25],
            ["name" => "Ifako-Ijaiye", "geo_state_id" => 25],
            ["name" => "Ikeja", "geo_state_id" => 25],
            ["name" => "Ikorodu", "geo_state_id" => 25],
            ["name" => "Kosofe", "geo_state_id" => 25],
            ["name" => "Lagos Island", "geo_state_id" => 25],
            ["name" => "Lagos Mainland", "geo_state_id" => 25],
            ["name" => "Mushin", "geo_state_id" => 25],
            ["name" => "Ojo", "geo_state_id" => 25],
            ["name" => "Oshodi-Isolo", "geo_state_id" => 25],
            ["name" => "Shomolu", "geo_state_id" => 25],
            ["name" => "Akwanga", "geo_state_id" => 26],
            ["name" => "Awe", "geo_state_id" => 26],
            ["name" => "Doma", "geo_state_id" => 26],
            ["name" => "Karu", "geo_state_id" => 26],
            ["name" => "Keana", "geo_state_id" => 26],
            ["name" => "Keffi", "geo_state_id" => 26],
            ["name" => "Kokona", "geo_state_id" => 26],
            ["name" => "Lafia", "geo_state_id" => 26],
            ["name" => "Nasarawaa", "geo_state_id" => 26],
            ["name" => "Nasarawa Egon", "geo_state_id" => 26],
            ["name" => "Obii", "geo_state_id" => 26],
            ["name" => "Toto", "geo_state_id" => 26],
            ["name" => "Wamba", "geo_state_id" => 26],
            ["name" => "Agaie", "geo_state_id" => 27],
            ["name" => "Agwara", "geo_state_id" => 27],
            ["name" => "Bida", "geo_state_id" => 27],
            ["name" => "Borgu", "geo_state_id" => 27],
            ["name" => "Bosso", "geo_state_id" => 27],
            ["name" => "Chanchaga", "geo_state_id" => 27],
            ["name" => "Edati", "geo_state_id" => 27],
            ["name" => "Gbako", "geo_state_id" => 27],
            ["name" => "Gurara", "geo_state_id" => 27],
            ["name" => "Katcha", "geo_state_id" => 27],
            ["name" => "Kontagora", "geo_state_id" => 27],
            ["name" => "Lapai", "geo_state_id" => 27],
            ["name" => "Lavun", "geo_state_id" => 27],
            ["name" => "Magama", "geo_state_id" => 27],
            ["name" => "Mariga", "geo_state_id" => 27],
            ["name" => "Mashegu", "geo_state_id" => 27],
            ["name" => "Mokwa", "geo_state_id" => 27],
            ["name" => "Moya", "geo_state_id" => 27],
            ["name" => "Paikoro", "geo_state_id" => 27],
            ["name" => "Rafi", "geo_state_id" => 27],
            ["name" => "Rijau", "geo_state_id" => 27],
            ["name" => "Shiroro", "geo_state_id" => 27],
            ["name" => "Suleja", "geo_state_id" => 27],
            ["name" => "Tafa", "geo_state_id" => 27],
            ["name" => "Wushishi", "geo_state_id" => 27],
            ["name" => "Abeokuta North", "geo_state_id" => 28],
            ["name" => "Abeokuta South", "geo_state_id" => 28],
            ["name" => "Ado-Odo/Ota", "geo_state_id" => 28],
            ["name" => "Egbado North", "geo_state_id" => 28],
            ["name" => "Egbado South", "geo_state_id" => 28],
            ["name" => "Ewekoro", "geo_state_id" => 28],
            ["name" => "Ifo", "geo_state_id" => 28],
            ["name" => "Ijebu East", "geo_state_id" => 28],
            ["name" => "Ijebu North", "geo_state_id" => 28],
            ["name" => "Ijebu North East", "geo_state_id" => 28],
            ["name" => "Ijebu Ode", "geo_state_id" => 28],
            ["name" => "Ikenne", "geo_state_id" => 28],
            ["name" => "Imeko Afon", "geo_state_id" => 28],
            ["name" => "Ipokia", "geo_state_id" => 28],
            ["name" => "Obafemi Owode", "geo_state_id" => 28],
            ["name" => "Odeda", "geo_state_id" => 28],
            ["name" => "Odogbolu", "geo_state_id" => 28],
            ["name" => "Ogun Waterside", "geo_state_id" => 28],
            ["name" => "Remo North", "geo_state_id" => 28],
            ["name" => "Shagamu", "geo_state_id" => 28],
            ["name" => "Akoko North-East", "geo_state_id" => 29],
            ["name" => "Akoko North-West", "geo_state_id" => 29],
            ["name" => "Akoko South-West", "geo_state_id" => 29],
            ["name" => "Akoko South-East", "geo_state_id" => 29],
            ["name" => "Akure North", "geo_state_id" => 29],
            ["name" => "Akure South", "geo_state_id" => 29],
            ["name" => "Ese Odo", "geo_state_id" => 29],
            ["name" => "Idanre", "geo_state_id" => 29],
            ["name" => "Ifedore", "geo_state_id" => 29],
            ["name" => "Ilaje", "geo_state_id" => 29],
            ["name" => "Ile Oluji/Okeigbo", "geo_state_id" => 29],
            ["name" => "Irele", "geo_state_id" => 29],
            ["name" => "Odigbo", "geo_state_id" => 29],
            ["name" => "Okitipupa", "geo_state_id" => 29],
            ["name" => "Ondo East", "geo_state_id" => 29],
            ["name" => "Ondo West", "geo_state_id" => 29],
            ["name" => "Ose", "geo_state_id" => 29],
            ["name" => "Owo", "geo_state_id" => 29],
            ["name" => "Atakunmosa East", "geo_state_id" => 30],
            ["name" => "Atakunmosa West", "geo_state_id" => 30],
            ["name" => "Aiyedaade", "geo_state_id" => 30],
            ["name" => "Aiyedire", "geo_state_id" => 30],
            ["name" => "Boluwaduro", "geo_state_id" => 30],
            ["name" => "Boripe", "geo_state_id" => 30],
            ["name" => "Ede North", "geo_state_id" => 30],
            ["name" => "Ede South", "geo_state_id" => 30],
            ["name" => "Ife Central", "geo_state_id" => 30],
            ["name" => "Ife East", "geo_state_id" => 30],
            ["name" => "Ife North", "geo_state_id" => 30],
            ["name" => "Ife South", "geo_state_id" => 30],
            ["name" => "Egbedore", "geo_state_id" => 30],
            ["name" => "Ejigbo", "geo_state_id" => 30],
            ["name" => "Ifedayo", "geo_state_id" => 30],
            ["name" => "Ifelodunn", "geo_state_id" => 30],
            ["name" => "Ila", "geo_state_id" => 30],
            ["name" => "Ilesa East", "geo_state_id" => 30],
            ["name" => "Ilesa West", "geo_state_id" => 30],
            ["name" => "Irepodunn", "geo_state_id" => 30],
            ["name" => "Irewole", "geo_state_id" => 30],
            ["name" => "Isokan", "geo_state_id" => 30],
            ["name" => "Iwo", "geo_state_id" => 30],
            ["name" => "Obokun", "geo_state_id" => 30],
            ["name" => "Odo Otin", "geo_state_id" => 30],
            ["name" => "Ola Oluwa", "geo_state_id" => 30],
            ["name" => "Olorunda", "geo_state_id" => 30],
            ["name" => "Oriade", "geo_state_id" => 30],
            ["name" => "Orolu", "geo_state_id" => 30],
            ["name" => "Osogbo", "geo_state_id" => 30],
            ["name" => "Afijio", "geo_state_id" => 31],
            ["name" => "Akinyele", "geo_state_id" => 31],
            ["name" => "Atiba", "geo_state_id" => 31],
            ["name" => "Atigbo", "geo_state_id" => 31],
            ["name" => "Egbeda", "geo_state_id" => 31],
            ["name" => "Ibadan North", "geo_state_id" => 31],
            ["name" => "Ibadan North-East", "geo_state_id" => 31],
            ["name" => "Ibadan North-West", "geo_state_id" => 31],
            ["name" => "Ibadan South-East", "geo_state_id" => 31],
            ["name" => "Ibadan South-West", "geo_state_id" => 31],
            ["name" => "Ibarapa Central", "geo_state_id" => 31],
            ["name" => "Ibarapa East", "geo_state_id" => 31],
            ["name" => "Ibarapa North", "geo_state_id" => 31],
            ["name" => "Ido", "geo_state_id" => 31],
            ["name" => "Irepo", "geo_state_id" => 31],
            ["name" => "Iseyin", "geo_state_id" => 31],
            ["name" => "Itesiwaju", "geo_state_id" => 31],
            ["name" => "Iwajowa", "geo_state_id" => 31],
            ["name" => "Kajola", "geo_state_id" => 31],
            ["name" => "Lagelu", "geo_state_id" => 31],
            ["name" => "Ogbomosho North", "geo_state_id" => 31],
            ["name" => "Ogbomosho South", "geo_state_id" => 31],
            ["name" => "Ogo Oluwa", "geo_state_id" => 31],
            ["name" => "Olorunsogo", "geo_state_id" => 31],
            ["name" => "Oluyole", "geo_state_id" => 31],
            ["name" => "Ona Ara", "geo_state_id" => 31],
            ["name" => "Orelope", "geo_state_id" => 31],
            ["name" => "Ori Ire", "geo_state_id" => 31],
            ["name" => "Oyo", "geo_state_id" => 31],
            ["name" => "Oyo East", "geo_state_id" => 31],
            ["name" => "Saki East", "geo_state_id" => 31],
            ["name" => "Saki West", "geo_state_id" => 31],
            ["name" => "Bokkos", "geo_state_id" => 32],
            ["name" => "Barkin Ladi", "geo_state_id" => 32],
            ["name" => "Basa", "geo_state_id" => 32],
            ["name" => "Jos East", "geo_state_id" => 32],
            ["name" => "Jos North", "geo_state_id" => 32],
            ["name" => "Jos South", "geo_state_id" => 32],
            ["name" => "Kanam", "geo_state_id" => 32],
            ["name" => "Kanke", "geo_state_id" => 32],
            ["name" => "Langtang South", "geo_state_id" => 32],
            ["name" => "Langtang North", "geo_state_id" => 32],
            ["name" => "Mangu", "geo_state_id" => 32],
            ["name" => "Mikang", "geo_state_id" => 32],
            ["name" => "Pankshin", "geo_state_id" => 32],
            ["name" => "Qua'an Pan", "geo_state_id" => 32],
            ["name" => "Riyom", "geo_state_id" => 32],
            ["name" => "Shendam", "geo_state_id" => 32],
            ["name" => "Wase", "geo_state_id" => 32],
            ["name" => "Abua/Odual", "geo_state_id" => 33],
            ["name" => "Ahoada East", "geo_state_id" => 33],
            ["name" => "Ahoada West", "geo_state_id" => 33],
            ["name" => "Akuku-Toru", "geo_state_id" => 33],
            ["name" => "Andoni", "geo_state_id" => 33],
            ["name" => "Asari-Toru", "geo_state_id" => 33],
            ["name" => "Bonny", "geo_state_id" => 33],
            ["name" => "Degema", "geo_state_id" => 33],
            ["name" => "Eleme", "geo_state_id" => 33],
            ["name" => "Emuoha", "geo_state_id" => 33],
            ["name" => "Etche", "geo_state_id" => 33],
            ["name" => "Gokana", "geo_state_id" => 33],
            ["name" => "Ikwerre", "geo_state_id" => 33],
            ["name" => "Khana", "geo_state_id" => 33],
            ["name" => "Obio/Akpor", "geo_state_id" => 33],
            ["name" => "Ogba/Egbema/Ndoni", "geo_state_id" => 33],
            ["name" => "Ogu/Bolo", "geo_state_id" => 33],
            ["name" => "Okrika", "geo_state_id" => 33],
            ["name" => "Omuma", "geo_state_id" => 33],
            ["name" => "Opobo/Nkoro", "geo_state_id" => 33],
            ["name" => "Oyigbo", "geo_state_id" => 33],
            ["name" => "Port Harcourt", "geo_state_id" => 33],
            ["name" => "Tai", "geo_state_id" => 33],
            ["name" => "Binji", "geo_state_id" => 34],
            ["name" => "Bodinga", "geo_state_id" => 34],
            ["name" => "Dange Shuni", "geo_state_id" => 34],
            ["name" => "Gada", "geo_state_id" => 34],
            ["name" => "Goronyo", "geo_state_id" => 34],
            ["name" => "Gudu", "geo_state_id" => 34],
            ["name" => "Gwadabawa", "geo_state_id" => 34],
            ["name" => "Illela", "geo_state_id" => 34],
            ["name" => "Isa", "geo_state_id" => 34],
            ["name" => "Kebbe", "geo_state_id" => 34],
            ["name" => "Kware", "geo_state_id" => 34],
            ["name" => "Rabah", "geo_state_id" => 34],
            ["name" => "Sabon Birni", "geo_state_id" => 34],
            ["name" => "Shagari", "geo_state_id" => 34],
            ["name" => "Silame", "geo_state_id" => 34],
            ["name" => "Sokoto North", "geo_state_id" => 34],
            ["name" => "Sokoto South", "geo_state_id" => 34],
            ["name" => "Tambuwal", "geo_state_id" => 34],
            ["name" => "Tangaza", "geo_state_id" => 34],
            ["name" => "Tureta", "geo_state_id" => 34],
            ["name" => "Wamako", "geo_state_id" => 34],
            ["name" => "Wurno", "geo_state_id" => 34],
            ["name" => "Yabo", "geo_state_id" => 34],
            ["name" => "Ardo Kola", "geo_state_id" => 35],
            ["name" => "Bali", "geo_state_id" => 35],
            ["name" => "Donga", "geo_state_id" => 35],
            ["name" => "Gashaka", "geo_state_id" => 35],
            ["name" => "Gassol", "geo_state_id" => 35],
            ["name" => "Ibi", "geo_state_id" => 35],
            ["name" => "Jalingo", "geo_state_id" => 35],
            ["name" => "Karim Lamido", "geo_state_id" => 35],
            ["name" => "Kumi", "geo_state_id" => 35],
            ["name" => "Lau", "geo_state_id" => 35],
            ["name" => "Sardauna", "geo_state_id" => 35],
            ["name" => "Takum", "geo_state_id" => 35],
            ["name" => "Ussa", "geo_state_id" => 35],
            ["name" => "Wukari", "geo_state_id" => 35],
            ["name" => "Yorro", "geo_state_id" => 35],
            ["name" => "Zing", "geo_state_id" => 35],
            ["name" => "Bade", "geo_state_id" => 36],
            ["name" => "Bursari", "geo_state_id" => 36],
            ["name" => "Damaturu", "geo_state_id" => 36],
            ["name" => "Fika", "geo_state_id" => 36],
            ["name" => "Fune", "geo_state_id" => 36],
            ["name" => "Geidam", "geo_state_id" => 36],
            ["name" => "Gujba", "geo_state_id" => 36],
            ["name" => "Gulani", "geo_state_id" => 36],
            ["name" => "Jakusko", "geo_state_id" => 36],
            ["name" => "Karasuwa", "geo_state_id" => 36],
            ["name" => "Machina", "geo_state_id" => 36],
            ["name" => "Nangere", "geo_state_id" => 36],
            ["name" => "Nguru", "geo_state_id" => 36],
            ["name" => "Potiskum", "geo_state_id" => 36],
            ["name" => "Tarmuwa", "geo_state_id" => 36],
            ["name" => "Yunusari", "geo_state_id" => 36],
            ["name" => "Yusufari", "geo_state_id" => 36],
            ["name" => "Anka", "geo_state_id" => 37],
            ["name" => "Bakura", "geo_state_id" => 37],
            ["name" => "Birnin Magaji/Kiyaw", "geo_state_id" => 37],
            ["name" => "Bukkuyum", "geo_state_id" => 37],
            ["name" => "Bungudu", "geo_state_id" => 37],
            ["name" => "Gummi", "geo_state_id" => 37],
            ["name" => "Gusau", "geo_state_id" => 37],
            ["name" => "Kaura Namoda", "geo_state_id" => 37],
            ["name" => "Maradun", "geo_state_id" => 37],
            ["name" => "Maru", "geo_state_id" => 37],
            ["name" => "Shinkafi", "geo_state_id" => 37],
            ["name" => "Talata Mafara", "geo_state_id" => 37],
            ["name" => "Chafe", "geo_state_id" => 37],
            ["name" => "Zurmi", "geo_state_id" => 37],
            ["name" => "Abaji", "geo_state_id" => 1],
            ["name" => "Bwari", "geo_state_id" => 1],
            ["name" => "Gwagwalada", "geo_state_id" => 1],
            ["name" => "Kuje", "geo_state_id" => 1],
            ["name" => "Kwali", "geo_state_id" => 1],
            ["name" => "Municipal Area Council", "geo_state_id" => 1]
        ]);

    }
}