<?php

namespace Database\Seeders;

use App\Models\Nationality;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            'American',
            'Canadian',
            'British',
            'Australian',
            'French',
            'German',
            'Spanish',
            'Italian',
            'Chinese',
            'Japanese',
            'Korean',
            'Indian',
            'Brazilian',
            'Mexican',
            'Russian',
            'South African',
            'Nigerian',
            'Egyptian',
            'Kenyan',
            'Ghanaian',
            'Saudi Arabian',
            'Emirati',
            'Turkish',
            'Iranian',
            'Iraqi',
            'Israeli',
            'Palestinian',
            'Lebanese',
            'Jordanian',
            'Syrian',
            'Indonesian',
            'Malaysian',
            'Singaporean',
            'Thai',
            'Vietnamese',
            'Filipino',
            'Argentinian',
            'Chilean',
            'Colombian',
            'Peruvian',
            'Venezuelan',
            'South Korean',
            'North Korean',
            'New Zealander',
            'Dutch',
            'Swedish',
            'Norwegian',
            'Danish',
            'Finnish',
            'Icelandic',
            'Portuguese',
            'Swiss',
            'Belgian',
            'Austrian',
            'Greek',
            'Czech',
            'Polish',
            'Hungarian',
            'Romanian',
            'Bulgarian',
            'Croatian',
            'Serbian',
            'Slovenian',
            'Slovak',
            'Ukrainian',
            'Belarusian',
            'Lithuanian',
            'Latvian',
            'Estonian',
            'Georgian',
            'Armenian',
            'Azerbaijani',
            'Kazakh',
            'Uzbek',
            'Turkmen',
            'Kyrgyz',
            'Tajik',
            'Afghan',
            'Pakistani',
            'Bangladeshi',
            'Sri Lankan',
            'Nepali',
            'Bhutanese',
            'Maldivian',
            'Mongolian',
            'Myanmar',
            'Laotian',
            'Cambodian',
            'Timorese',
            'Papua New Guinean',
            'Solomon Islander',
            'Fijian',
            'Tongan',
            'Samoan',
            'Tuvaluan',
            'Kiribati',
            'Marshallese',
            'Palauan',
            'Tahitian',
            'Cook Islander',
            'Niuean',
            'Tokelauan',
            'Micronesian',
            'Marshall Islander',
            'Nauruan',
            'Palauan',
            'Tuvaluan',
            'Kiribati',
            'Tongan',
            'Samoan',
            'Tuvaluan',
            'Kiribati',
            'Marshallese',
            'Palauan',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
            'Ugandan',
            'Rwandan',
            'Burundian',
            'Kenyan',
            'Tanzanian',
            'Seychellois',
            'Mauritian',
            'Comorian',
            'Malagasy',
            'Mozambican',
            'Namibian',
            'Botswanan',
            'Zimbabwean',
            'Zambian',
            'Angolan',
            'Equatorial Guinean',
            'Gabonese',
            'Cameroonian',
            'Central African',
            'Chadian',
            'Sudanese',
            'South Sudanese',
            'Eritrean',
            'Djiboutian',
            'Somali',
            'Ethiopian',
        ];

        foreach ($nationalities as $nationality) {
            Nationality::create(['nationality' => $nationality]);
        }

    }
}
